repo_name: JackBot
site_name: JackBot
site_author: Cairo Mitchell-Acason
site_url: https://jackbot.js.org
site_description: This is the official website and documentation for JackBot. JackBot is a Discord Bot full of memes, quotes and many other things that are about or relevant to the YouTuber JackSucksAtLife.
google_analytics: ['UA-121552805-1', 'cairo2k18.github.io/jackbot']
pages:
    - Home: index.md
    - Status: status.md
    - Commands: commands.md
    - Update Logs: updatelogs.md
    - Bug Report: bugreport.md
copyright: Copyright &copy; 2018 <a href="https://twitter.com/CairoNZ">Cairo Mitchell-Acason</a><br>Copyright &copy; 2018 Twitter, Inc. Graphics licensed under <a href="https://creativecommons.org/licenses/by/4.0/">CC-BY 4.0</a><br>You may view the JackBot Legal website by clicking <a href="https://jackbot.js.org/legal">here</a>
plugins:
    - search
theme:
  name: 'material'
  custom_dir: 'theme'
  favicon: 'img/favicon.ico'
  logo: 'img/robot.svg'
  palette:
    primary: 'red'
    accent: 'blue'
markdown_extensions:
  - meta
  - footnotes
  - codehilite
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  - stylesheets/twemoji-awesome.css
